
package ventana;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author victorpointud
 */

public class FileChooser extends javax.swing.JFrame {

    /**
    *
    *  Inicio.
    */
    public FileChooser() {    
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        PathDisplay = new javax.swing.JTextField();
        InfoFileChooserWindow = new javax.swing.JLabel();
        FileChooserButton = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        InfoFileChooserWindow1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PathDisplay.setEditable(false);
        PathDisplay.setBackground(new java.awt.Color(255, 255, 255));
        PathDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PathDisplayActionPerformed(evt);
            }
        });
        jPanel1.add(PathDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 330, -1));

        InfoFileChooserWindow.setBackground(new java.awt.Color(255, 255, 255));
        InfoFileChooserWindow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InfoFileChooserWindow.setForeground(new java.awt.Color(255, 255, 255));
        InfoFileChooserWindow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InfoFileChooserWindow.setText("Luego de elegir el archivo vaya al menú");
        jPanel1.add(InfoFileChooserWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 370, 30));

        FileChooserButton.setBackground(new java.awt.Color(0, 204, 204));
        FileChooserButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        FileChooserButton.setText("Cargar Archivo");
        FileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooserButtonActionPerformed(evt);
            }
        });
        jPanel1.add(FileChooserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        Next.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Next.setText("SIGUIENTE");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        jPanel1.add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 140, 40));

        InfoFileChooserWindow1.setBackground(new java.awt.Color(255, 255, 255));
        InfoFileChooserWindow1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InfoFileChooserWindow1.setForeground(new java.awt.Color(255, 255, 255));
        InfoFileChooserWindow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InfoFileChooserWindow1.setText("Debes elegir un archivo para cargar el programa. ");
        jPanel1.add(InfoFileChooserWindow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 370, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/v1016-c-08_1-ksh6mza3.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
    *
    *  Muestra la dirección del archivo seleccionado de tu dispositivo.
    */
    private void PathDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PathDisplayActionPerformed

    }//GEN-LAST:event_PathDisplayActionPerformed

    /**
    *
    *  Muestra el seleccionador de archivo del usuario de su dispositivo.
    */
    private void FileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooserButtonActionPerformed
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text Files","txt");
        this.fileChooser.setFileFilter(filter);
        int returnVal = this.fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String filename = this.fileChooser.getSelectedFile().getAbsolutePath();
            this.PathDisplay.setText(filename);
        }
    }//GEN-LAST:event_FileChooserButtonActionPerformed
    
    /**
    *  Muestra la ventana menú.
    */
    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        
        String filename = this.PathDisplay.getText();
        if(!filename.equals("")){
            Menu menu = new Menu(filename);
            this.setVisible(false);
            menu.setVisible(true);
        } else {
        }
    }//GEN-LAST:event_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileChooser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FileChooserButton;
    private javax.swing.JLabel InfoFileChooserWindow;
    private javax.swing.JLabel InfoFileChooserWindow1;
    private javax.swing.JButton Next;
    private javax.swing.JTextField PathDisplay;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
