
package ventana;

import proyectoislas.UndirectedGraph;

/**
 *
 * @author CarlosEGonR
 */

public class Information extends javax.swing.JFrame {
    
    /**
    *
    *  Inicio.
    */
    
    UndirectedGraph graph;
    
    public Information() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    public Information(UndirectedGraph graph) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        this.graph = graph;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DFS = new javax.swing.JButton();
        BFS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoText = new javax.swing.JTextArea();
        Menu = new javax.swing.JButton();
        Bridges = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DFS.setBackground(new java.awt.Color(0, 204, 204));
        DFS.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        DFS.setText("DFS");
        DFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFSActionPerformed(evt);
            }
        });
        jPanel1.add(DFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 160, 70));

        BFS.setBackground(new java.awt.Color(0, 204, 204));
        BFS.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BFS.setText("BFS");
        BFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFSActionPerformed(evt);
            }
        });
        jPanel1.add(BFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 70));

        InfoText.setEditable(false);
        InfoText.setColumns(20);
        InfoText.setRows(5);
        jScrollPane1.setViewportView(InfoText);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 500, 150));

        Menu.setBackground(new java.awt.Color(255, 255, 0));
        Menu.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Menu.setText("MENU");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 100, 40));

        Bridges.setBackground(new java.awt.Color(0, 204, 204));
        Bridges.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Bridges.setText("PUENTES");
        Bridges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BridgesActionPerformed(evt);
            }
        });
        jPanel1.add(Bridges, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 160, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/v1016-c-08_1-ksh6mza3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
    *
    *  Realiza el recorrido en forma DFS.
    */
    private void DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFSActionPerformed

        String islands = "";
        int nIsland = 1;
        int n = this.graph.nodesLength();
        boolean[] visited = new boolean[n];
        for(int i=0; i < n; i++)
            visited[i] = false;
        for (int i = 0; i < n; ++i) {
            if (!visited[i]) {
                islands += ("Isla " + nIsland + ": \n" +  this.graph.DFS(i, visited) + "\n\n");
                nIsland++;
            }
        }
        this.InfoText.setText(islands);
    }//GEN-LAST:event_DFSActionPerformed

    /**
    *
    *  Realiza el recorrido en forma BFS.
    */
    private void BFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFSActionPerformed
        
        String islands = "";
        int nIsland = 1;
        int n = this.graph.nodesLength();
        boolean[] visited = new boolean[n];
        for(int i=0; i < n; i++)
            visited[i] = false;
        for (int i = 0; i < n; ++i) {
            if (!visited[i]) {
                islands += ("Isla " + nIsland + ": \n" + this.graph.BFS(i, visited) + "\n\n");
                nIsland++;
            }
        }  
        this.InfoText.setText(islands);
    }//GEN-LAST:event_BFSActionPerformed

    /**
    *
    *  Muestra la ventana menú.
    */
    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        
        Menu mw = new Menu (this.graph);
        this.setVisible(false);
        mw.setVisible(true);
    }//GEN-LAST:event_MenuActionPerformed

    /**
    *
    *  Muestra los puentes existentes.
    */
    private void BridgesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BridgesActionPerformed
        
        String bridges = this.graph.getBridges();
        this.InfoText.setText(bridges);
    }//GEN-LAST:event_BridgesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BFS;
    private javax.swing.JButton Bridges;
    private javax.swing.JButton DFS;
    private javax.swing.JTextArea InfoText;
    private javax.swing.JButton Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
