
package ventana;

import proyectoislas.UndirectedGraph;
import java.io.FileWriter; 
import java.io.IOException; 
import javax.swing.JFileChooser;

/**
 *
 * @author Juan2808
 */

public class Menu extends javax.swing.JFrame {
    
    /**
    *
    *  Inicio.
    */
    
    UndirectedGraph graph;
    
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    public Menu(String filename){
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        graph = new UndirectedGraph(filename);
    }
    
    public Menu(UndirectedGraph graph){
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.graph = graph;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        Information = new javax.swing.JButton();
        Graph = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        End = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Information.setBackground(new java.awt.Color(0, 204, 204));
        Information.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Information.setText("INFORMACIÓN");
        Information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformationActionPerformed(evt);
            }
        });
        jPanel1.add(Information, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 170, 60));

        Graph.setBackground(new java.awt.Color(0, 204, 204));
        Graph.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Graph.setText("GRAFO");
        Graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphActionPerformed(evt);
            }
        });
        jPanel1.add(Graph, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 160, 60));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menú");
        jLabel3.setMaximumSize(new java.awt.Dimension(115, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(115, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(140, 30));
        jLabel3.setRequestFocusEnabled(false);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 260, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        Save.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Save.setText("GUARDAR");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 130, 50));

        End.setBackground(new java.awt.Color(255, 255, 0));
        End.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        End.setText("SALIR");
        End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndActionPerformed(evt);
            }
        });
        jPanel1.add(End, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 140, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/v1016-c-08_1-ksh6mza3.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 530, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    *
    *  Guarda la información donde el usario seleccione.
    */
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed

        int returnVal = this.jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String filename = this.jFileChooser1.getSelectedFile().getAbsolutePath();
            try {
                FileWriter myWriter = new FileWriter(filename);
                myWriter.write("Usuarios\n");
                this.graph.writeNodes(myWriter);
                myWriter.write("Relaciones\n");
                this.graph.writeEdges(myWriter);
                myWriter.close();
              } catch (IOException e) {
                e.printStackTrace();
              }
        }

    }//GEN-LAST:event_SaveActionPerformed

    /**
    *
    *  Muestra la ventana grafo.
    */
    private void GraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphActionPerformed

        Graphs gw = new Graphs(graph);
        this.setVisible(false);
        gw.setVisible(true);

    }//GEN-LAST:event_GraphActionPerformed

    
    /**
    *
    *  Muestra la ventana para ver los recorridos BFS, DFS y Puentes.
    */
    private void InformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformationActionPerformed

        Information rw = new Information(graph);
        this.setVisible(false);
        rw.setVisible(true);
    }//GEN-LAST:event_InformationActionPerformed

    /**
    *
    *  Realiza  finalización del programa.
    */
    private void EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndActionPerformed

        System.exit(0);
    }//GEN-LAST:event_EndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton End;
    private javax.swing.JButton Graph;
    private javax.swing.JButton Information;
    private javax.swing.JButton Save;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
