
package ventana;

import proyectohotel.HashTable;
import proyectohotel.LinkedList;
import proyectohotel.RoomHistory;
import proyectohotel.ReservationList;
import proyectohotel.RoomOwner;

/*
* Juan2808
*/
    
/*
* JFrame para el menú.
*/

public class Menu extends javax.swing.JFrame {
    
    RoomHistory history;
    ReservationList reservations;
    HashTable<String, RoomOwner> actualGuests;
    LinkedList<RoomOwner> actualReservations;
    
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    public Menu(RoomHistory history, ReservationList reservations, HashTable<String, RoomOwner> actualGuests, LinkedList<RoomOwner> actualReservations) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.history = history;
        this.reservations = reservations;
        this.actualGuests = actualGuests;
        this.actualReservations = actualReservations;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        Information = new javax.swing.JButton();
        CheckOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        End = new javax.swing.JButton();
        CheckIn = new javax.swing.JButton();
        Register = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Information.setBackground(new java.awt.Color(0, 204, 204));
        Information.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Information.setText("Información");
        Information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformationActionPerformed(evt);
            }
        });
        jPanel1.add(Information, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 160, 60));

        CheckOut.setBackground(new java.awt.Color(0, 204, 204));
        CheckOut.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        CheckOut.setText("Check-Out");
        CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutActionPerformed(evt);
            }
        });
        jPanel1.add(CheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 160, 60));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menú");
        jLabel3.setMaximumSize(new java.awt.Dimension(115, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(115, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(140, 30));
        jLabel3.setRequestFocusEnabled(false);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 260, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        End.setBackground(new java.awt.Color(255, 255, 0));
        End.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        End.setText("Salir");
        End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndActionPerformed(evt);
            }
        });
        jPanel1.add(End, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 140, 40));

        CheckIn.setBackground(new java.awt.Color(0, 204, 204));
        CheckIn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        CheckIn.setText("Check-In");
        CheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInActionPerformed(evt);
            }
        });
        jPanel1.add(CheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 160, 60));

        Register.setBackground(new java.awt.Color(0, 204, 204));
        Register.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Register.setText("Huéspedes");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 160, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/v1016-c-08_1-ksh6mza3.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    *  Muestra la ventana información.
    */
    
    private void InformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformationActionPerformed

        Information i = new Information(history, reservations, actualGuests, actualReservations);
        this.setVisible(false);
        i.setVisible(true);

    }//GEN-LAST:event_InformationActionPerformed

    /*
    *  Muestra la ventana para hacer check-Out.
    */
    
    private void CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutActionPerformed

        CheckOut co = new CheckOut(history, reservations, actualGuests, actualReservations);
        this.setVisible(false);
        co.setVisible(true);
    }//GEN-LAST:event_CheckOutActionPerformed

    /*
    *  Realiza  finalización del programa.
    */
    
    private void EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndActionPerformed

        System.exit(0);
    }//GEN-LAST:event_EndActionPerformed

    /*
    *  Muestra la ventana para hacer check-In.
    */
    
    private void CheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInActionPerformed
        CheckIn ci = new CheckIn(history, reservations, actualGuests, actualReservations);
        this.setVisible(false);
        ci.setVisible(true);
    }//GEN-LAST:event_CheckInActionPerformed

    /*
    *  Muestra la ventana registro.
    */
    
    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        
        Register r = new Register(history, reservations, actualGuests, actualReservations);
        this.setVisible(false);
        r.setVisible(true);
    }//GEN-LAST:event_RegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckIn;
    private javax.swing.JButton CheckOut;
    private javax.swing.JButton End;
    private javax.swing.JButton Information;
    private javax.swing.JButton Register;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
