/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import mainpackage.DoubleCircularList;
import mainpackage.NodeRadioStation;

/**
 *
 * @author victorpointud
 */
public class FirstWindow extends javax.swing.JFrame {

    /**
     * Creates new form FirstWindow
     */
    DoubleCircularList AmList;
    DoubleCircularList FmList;
    NodeRadioStation AmNode;
    NodeRadioStation FmNode;
    
    boolean isAm = true;
    public FirstWindow() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        NextStationButton = new javax.swing.JButton();
        PrevStationButtons = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        NameTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        MusicTextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        NumberTextArea = new javax.swing.JTextArea();
        AmFmButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        FavButton = new javax.swing.JButton();
        FavGotoButton = new javax.swing.JButton();
        FileChooserbtn = new javax.swing.JButton();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NextStationButton.setText(">");
        NextStationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextStationButtonActionPerformed(evt);
            }
        });

        PrevStationButtons.setText("<");
        PrevStationButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrevStationButtonsActionPerformed(evt);
            }
        });

        NameTextArea.setColumns(20);
        NameTextArea.setRows(5);
        jScrollPane1.setViewportView(NameTextArea);

        MusicTextArea.setColumns(20);
        MusicTextArea.setRows(5);
        jScrollPane3.setViewportView(MusicTextArea);

        NumberTextArea.setColumns(20);
        NumberTextArea.setRows(5);
        jScrollPane5.setViewportView(NumberTextArea);

        AmFmButton.setText("Am/Fm");
        AmFmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmFmButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Presione para cambiar a radio Am o Fm.");

        FavButton.setText("Fav");
        FavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavButtonActionPerformed(evt);
            }
        });

        FavGotoButton.setText("Ir a Estacion Fav");
        FavGotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavGotoButtonActionPerformed(evt);
            }
        });

        FileChooserbtn.setText("Archivo");
        FileChooserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooserbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(PrevStationButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(AmFmButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NextStationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(88, 88, 88))))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(FavGotoButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FileChooserbtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FileChooserbtn)
                        .addGap(26, 26, 26)
                        .addComponent(FavButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(FavGotoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextStationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrevStationButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmFmButton))
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstWindow().setVisible(true);
            }
        });
    }
    
    private void AmFmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmFmButtonActionPerformed
        // TODO add your handling code here:
        if(isAm){
            isAm = false;
        }else{
            isAm = true;
        }
        this.refreshStations();
    }//GEN-LAST:event_AmFmButtonActionPerformed

    private void NextStationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextStationButtonActionPerformed
        // TODO add your handling code here:
        if(isAm){
            AmNode = AmNode.getNext();
        }else{
            FmNode = FmNode.getNext();
        }
        this.refreshStations();
    }//GEN-LAST:event_NextStationButtonActionPerformed

    private void PrevStationButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrevStationButtonsActionPerformed
        // TODO add your handling code here:
        if(isAm){
            AmNode = AmNode.getPrev();
        }else{
            FmNode = FmNode.getPrev();
        }
        this.refreshStations();
    }//GEN-LAST:event_PrevStationButtonsActionPerformed

    private void FavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavButtonActionPerformed
        // TODO add your handling code here:
        if(isAm){
            AmList.setFav(AmNode);
        }else{
            FmList.setFav(FmNode);
        }
    }//GEN-LAST:event_FavButtonActionPerformed

    private void FavGotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavGotoButtonActionPerformed
        // TODO add your handling code here:
        if(isAm){
            AmNode = AmList.getFav();
            if(AmNode == null){
                AmNode = AmList.getHead();
            }
        }else{
            FmNode = FmList.getFav();
            if(FmNode == null){
                FmNode = FmList.getHead();
            }
        }
        
        this.refreshStations();
    }//GEN-LAST:event_FavGotoButtonActionPerformed

    private void FileChooserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooserbtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int selection = fc.showOpenDialog(this);
        String path;
       if (selection == JFileChooser.APPROVE_OPTION) {
            path = fc.getSelectedFile().getAbsolutePath();
            DoubleCircularList[] output ;

        String outText = this.readText(path);
        DoubleCircularList TempList = this.CreateList(outText);
        System.out.println("aqui");
        TempList = this.OrderList(TempList);
        this.AmList = TempList;
        //System.out.println("aqui1");
        //output = this.SeparateAmFm(TempList);
        //this.AmList = output[0];
        //this.FmList = output[1];
        //this.refreshStations();
        
        }

    }//GEN-LAST:event_FileChooserbtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AmFmButton;
    private javax.swing.JButton FavButton;
    private javax.swing.JButton FavGotoButton;
    private javax.swing.JButton FileChooserbtn;
    private javax.swing.JTextArea MusicTextArea;
    private javax.swing.JTextArea NameTextArea;
    private javax.swing.JButton NextStationButton;
    private javax.swing.JTextArea NumberTextArea;
    private javax.swing.JButton PrevStationButtons;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables

    public void refreshStations(){
        if(isAm){
            
            MusicTextArea.setText(AmNode.getSong());
            NameTextArea.setText(AmNode.getName());
            NumberTextArea.setText(AmNode.getNumber());
            
        }else{
            
            MusicTextArea.setText(FmNode.getSong());
            NameTextArea.setText(FmNode.getName());
            NumberTextArea.setText(FmNode.getNumber());
            
        }
    }

    public DoubleCircularList getAmList() {
        return AmList;
    }

    public void setAmList(DoubleCircularList AmList) {
        this.AmList = AmList;
    }

    public DoubleCircularList getFmList() {
        return FmList;
    }

    public void setFmList(DoubleCircularList FmList) {
        this.FmList = FmList;
    }

    public NodeRadioStation getAmNode() {
        return AmNode;
    }

    public void setAmNode(NodeRadioStation AmNode) {
        this.AmNode = AmNode;
    }

    public NodeRadioStation getFmNode() {
        return FmNode;
    }

    public void setFmNode(NodeRadioStation FmNode) {
        this.FmNode = FmNode;
    }

//MainFunctions:
    
    
        
    public String readText(String path) {
        String line;
        String Text = "";
        if (path.equals("")) {
           //fix 
           return null;
        }
        File file = new File(path);
        try {
            if (!file.exists()) {
                file.createNewFile();
            } else {
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);
                while ((line = br.readLine()) != null) {
                    if (!line.isEmpty()) {
                        Text += line + "\n";
                    }
                }
                br.close();
                return Text;
            }
        } catch (Exception ex){
            return "";
        } 
        return Text;
    }
    
    
    public DoubleCircularList CreateList (String Text) {
        DoubleCircularList outList = new DoubleCircularList();
        
        if (!"".equals(Text)) {
                       
            String[] TextLine = Text.split("\n");
            for (int i = 0; i < TextLine.length; i++) {
                String[] aux = TextLine[i].split(",");
                NodeRadioStation NewStation = new NodeRadioStation(aux[0],aux[1],aux[2]);
                outList.insert(NewStation, 0);
            }
             
            return outList;
        }
        return null;
     }
     
     public DoubleCircularList OrderList(DoubleCircularList inList){
         
        DoubleCircularList outList = new DoubleCircularList();
        NodeRadioStation pointer = inList.getHead();
        
        for (int i = 0; i < inList.getTotal(); i++) {
            
            
            
            if(outList.getEmpty()){
                
                outList.insert(pointer, 0);
            }
            else{
                
                NodeRadioStation pointer2 = outList.getHead();
                float f = Float.parseFloat(pointer.getNumber());
                
                for (int j = 0; j < outList.getTotal(); j++){
                    
                    if(f > Float.parseFloat(pointer2.getNumber())){
                        outList.insert(pointer, outList.getTotal() + 1);
                    }
                    else if (f < Float.parseFloat(pointer2.getNumber())){
                        outList.insert(pointer, j);
                    }
                    else{
                        pointer2 = pointer2.getNext();
                    }
                }
                
            }
         pointer = pointer.getNext();
        }
        return outList;
     }
     
     public DoubleCircularList[] SeparateAmFm(DoubleCircularList inList){
         
         System.out.println("aqui2");
         NodeRadioStation pointer = inList.getHead();
         DoubleCircularList Amlist = new DoubleCircularList();
         DoubleCircularList Fmlist = new DoubleCircularList();
         DoubleCircularList[] output;
         output = new DoubleCircularList[2];
         System.out.println("aqui3");
         for (int i = 0; i < inList.getTotal(); i++) {
             
            System.out.println("aqui4");
             if(pointer.getNumber().contains(".")){
                 System.out.println("aqui5");
                 Fmlist.insert(pointer, i);
                 
             }else{
                 System.out.println("aqui6");
                 Amlist.insert(pointer, i);
                 
             }
             pointer = pointer.getNext();
         }
         output[0] = Amlist;
         output[1] = Fmlist;
         return output;
     }

    
}
