
package ventana;

import proyectohotel.HashTable;
import proyectohotel.LinkedList;
import proyectohotel.RoomHistory;
import proyectohotel.ReservationList;
import proyectohotel.RoomOwner;

/*
* victorpointud
*/
    
/*
* JFrame para mostrar la información.
*/

public class Information extends javax.swing.JFrame {

    RoomHistory history;
    ReservationList reservations;
    HashTable<String, RoomOwner> actualGuests;
    LinkedList<RoomOwner> actualReservations;
    
    public Information() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public Information(RoomHistory history, ReservationList reservations, HashTable<String, RoomOwner> actualState, LinkedList<RoomOwner> actualReservations) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.history = history;
        this.reservations = reservations;
        this.actualGuests = actualState;
        this.actualReservations = actualReservations;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RoomHistory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoText = new javax.swing.JTextArea();
        Back = new javax.swing.JButton();
        Reservation = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        RoomId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ClientId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomHistory.setBackground(new java.awt.Color(0, 204, 204));
        RoomHistory.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        RoomHistory.setText("Historial Habitación");
        RoomHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomHistoryActionPerformed(evt);
            }
        });
        jPanel1.add(RoomHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 230, 30));

        InfoText.setEditable(false);
        InfoText.setColumns(20);
        InfoText.setRows(5);
        jScrollPane1.setViewportView(InfoText);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 270, 220));

        Back.setBackground(new java.awt.Color(255, 255, 0));
        Back.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Back.setText("Retroceder");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 281, 180, 30));

        Reservation.setBackground(new java.awt.Color(0, 204, 204));
        Reservation.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Reservation.setText("Reservación");
        Reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationActionPerformed(evt);
            }
        });
        jPanel1.add(Reservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 160, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ingrese el número de habitación:");
        jLabel5.setMinimumSize(new java.awt.Dimension(240, 24));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, 20));
        jPanel1.add(RoomId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 190, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Información");
        jLabel6.setMaximumSize(new java.awt.Dimension(115, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(115, 25));
        jLabel6.setPreferredSize(new java.awt.Dimension(140, 30));
        jLabel6.setRequestFocusEnabled(false);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 310, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ingrese su cédula:");
        jLabel4.setMinimumSize(new java.awt.Dimension(240, 24));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, 20));

        ClientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientIdActionPerformed(evt);
            }
        });
        jPanel1.add(ClientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 190, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/v1016-c-08_1-ksh6mza3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /*
    *  Muestra la lista de huéspedes dada la habitación. Para ello busca por el número
    *  de habitación en el ABB con el histórico de las habitaciones
    */
    
    private void RoomHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomHistoryActionPerformed
        String numHab  = RoomId.getText();
        // Se busca la habitación en el ABB de las habitaciones y se obtiene su historico
        String roomHistory = history.getRoomHistory(numHab);
        InfoText.setText(roomHistory);
    }//GEN-LAST:event_RoomHistoryActionPerformed

    /*
    *  Muestra la ventana menú.
    */
    
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        
        Menu m = new Menu(history, reservations, actualGuests, actualReservations);
        this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /*
    *  Muestra la reservación dado la cédula. Para ello busca por el número
    *  de cédula en el ABB con las reservaciones hechas por los clientes.
    */
    
    private void ReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationActionPerformed
        String ci  = ClientId.getText();
        // Se busca la cedula en el ABB de reservaciones y se obtiene sus datos
        String reservationData = reservations.getReservationData(ci);
        InfoText.setText(reservationData);
    }//GEN-LAST:event_ReservationActionPerformed
    
    private void ClientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientIdActionPerformed
        
    }//GEN-LAST:event_ClientIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField ClientId;
    private javax.swing.JTextArea InfoText;
    private javax.swing.JButton Reservation;
    private javax.swing.JButton RoomHistory;
    private javax.swing.JTextField RoomId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
